//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public System.DateTime HistoryDate { get; set; }
        public string Field { get; set; }
        public int UserId { get; set; }
        public string PreviousValue { get; set; }
        public string CurrentValue { get; set; }
        public int TempId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Pieces Pieces { get; set; }
    }
}
