//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TempDataEntities : DbContext
    {
        public TempDataEntities()
            : base("name=TempDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Identifiers> Identifiers { get; set; }
        public virtual DbSet<Measures> Measures { get; set; }
        public virtual DbSet<Piece_Details> Piece_Details { get; set; }
        public virtual DbSet<Pieces> Pieces { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
